### ISSUE TITLE
Introduce SBOM Attestation for Container Artifact Provenance

### ISSUE THREAD

**Issue by jujaga** [bcgov/action-builder-ghcr#83]
With the rise of software supply chain risks, there is a growing need for the ability to attest for the provenance and origin for artifacts. Github provides a few mechanisms to assist with Software Bill of Material (SBOM) attestations. In order to provide another level of assurance for clients, we should consider adopting the use of the `actions/attest` action. An example use of it follows:

```yaml
    - name: Attest
      uses: actions/attest@v2.3.0
      id: attest
      with:
        subject-name: ghcr.io/${{ env.GH_USERNAME }}/${{ inputs.image_name }}
        subject-digest: ${{ steps.builder.outputs.digest }}
        predicate-type: 'https://in-toto.io/attestation/release/v0.1'
        predicate: '{"purl":"pkg:oci/${{ env.GH_USERNAME }}/${{ inputs.image_name }}"}'
```

One of the benefits of using the Attest action is that it has the ability to integrate with Github's existing facilities to declare artifact provenance. An example attestation can be seen [here](https://github.com/bcgov/nr-peach/attestations/7380917).

The key note is that the `subject-name` and `subject-digest` are declared, and includes information such as which github run built it, and which github action triggered the flow. These extra bits of information help assure clients that the image they use has been generated by a sanctioned and intended process, thereby improving our security posture, as clients would be able to check for matching sha256 digests and their attestations prior to deployment.

## References
- Detailed documentation: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
- https://github.com/bcgov/nr-peach/blob/main/.github/actions/build-push-container/action.yaml#L64-L71
- https://github.com/actions/attest
